package org.chatClient.fittings;

import lombok.Getter;

@Getter
public enum MySizePanel {
    HEIGHT_SIZE_WINDOW (600),
    WIDTH_SIZE_WINDOW (400),

    HEIGHT_SIZE_WINDOW_INIT (300),
    WIDTH_SIZE_WINDOW_INIT (350),

    HEIGHT_SIZE_PANEL_CORRESPONDENCE (300),
    WIDTH_SIZE_PANEL_CORRESPONDENCE (360),

    WIDTH_SIZE_SCROLL_CORRESPONDENCE(360),
    HEIGHT_SIZE_SCROLL_CORRESPONDENCE(300),

    WIDTH_SIZE_REQUEST_CORRESPONDENCE(360),
    HEIGHT_SIZE_REQUEST_CORRESPONDENCE(100),

    HEIGHT_SIZE_PANEL_MESSAGE (230),
    WIDTH_SIZE_PANEL_MESSAGE(400),

    HEIGHT_SIZE_AREA_MESSAGE (180),
    WIDTH_SIZE_AREA_MESSAGE(300);


    private int size;

    MySizePanel (int size){
        this.size= size;
    }
}
